### ISSUE TITLE
OAuth Redirect Urls point to localhost and port instead of domain

### ISSUE THREAD

**Issue by stvn1337** [YunoHost-Apps/n8n_ynh#10]
### Describe the bug

Can't set the WEBHOOK_URL and it defaults to localhost which causes OAuth redirect urls to not work. I have tried setting the Environement variables on the server hosting Yunohost as well as defining the variables in the settings file. 

### Context

- Hardware: VPS on Vultr
- YunoHost version: 4.3.3 Stable
- I have access to my server: SSH and Web Admin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no
- Using, or trying to install package version/branch: Master

### Steps to reproduce

- Install like normal
- Attempt to add Box node
- Oath credential redirect url will be localhost

### Expected behavior

* webhook_url would be set the same as host.

**Comment by brimwats** [comment]
seconding this as well

**Comment by brimwats** [comment]
seems it can be fixed with .env variables. not sure where to find or add them on yunohost yet https://docs.n8n.io/reference/environment-variables.html

**Comment by tituspijean** [comment]
Can you confirm it is fixed if you add, for example `N8N_HOST=your.domain.tld` in `/var/www/n8n/.env`?

**Comment by brimwats** [comment]
yes, i just figured it out the same way as @tituspijean except I added `WEBHOOK_URL=https://domain.tld/n8n/` to the env file. Is N8N_HOST better you think @tituspijean ?

this generates a Callback URL like https://domail.tld/n8n/rest/oauth2-credential/callback

**Comment by tituspijean** [comment]
Based off what I have just read [here](https://docs.n8n.io/getting-started/installation/advanced/configuration.html#webhook-url), I think your option is more suitable in case of reverse proxifying like we do with NGINX.

**Comment by brimwats** [comment]
I think this can be closed

**Comment by fflorent** [comment]
Indeed. Thanks for your feedback @brimwats and thanks @tituspijean for your fix!
Florent
