### ISSUE TITLE
n8n database.sqlite is more than 40gb

### ISSUE THREAD

**Issue by theRAGEhero** [YunoHost-Apps/n8n_ynh#18]
Hello,
my database.sqlite is very big and I just have some RSS feed bot on n8n.

![image](https://user-images.githubusercontent.com/39453005/160253653-2536dafe-debe-46ed-a22b-4a57ed2779f0.png)

I'm using YH 4.3.6.2 and the last version of n8n avalaible for YH.

I think it is related to this thread. https://community.n8n.io/t/why-is-my-database-so-big/7981/17

Would it be possible to fix it from the app? 
Thank you

**Comment by ericgaspar** [comment]
sqlite? I thought we were using mysql as database...
I added those extra env settings in this branch: https://github.com/YunoHost-Apps/n8n_ynh/tree/database

**Comment by fflorent** [comment]
Indeed, it's weird. The extra settings does not solve the issue, the database is still empty:
```
MariaDB [n8n]> show tables;
Empty set (0.001 sec)
```

**Comment by theRAGEhero** [comment]
Also my n8n db on Mysql is empty while the database.sqlite now is 50gb!

**Comment by ericgaspar** [comment]
n8n seems to be using sqlite by default...

**Comment by theRAGEhero** [comment]
Should I save my apps and reinstall it? It's becoming huge!

**Comment by fflorent** [comment]
Do you have many workflows? If not, I guess that is the best choice.

**Comment by theRAGEhero** [comment]
> Do you have many workflows? If not, I guess that is the best choice (EDIT: in case you cannot wait).

Just some. I removed it. Should now be working on mysql if I reinstall it?

**Comment by fflorent** [comment]
When the CI tell us that's OK, we should be good to merge:
https://github.com/YunoHost-Apps/n8n_ynh/pull/21#issuecomment-1082344401

Florent

**Comment by theRAGEhero** [comment]
I installed the testing version and now the n8n mysql db is populated, but it doesn't allow me to log in. I'm pretty sure about user and password.

**Comment by xplosionmind** [comment]
As noted in the log file itself, I should write in this issue that I am experiencing a problem while upgrading the app.

[Here is the full log](
https://paste.yunohost.org/raw/rakuwuzixu)

What should I do?
