### ISSUE TITLE
Installation slows/crashes the system

### ISSUE THREAD

**Issue by Krusty27** [YunoHost-Apps/n8n_ynh#25]
### Describe the bug

The installation of n8n is very slow, stuck at 'installing n8n', then the connection times out when trying to connect to the web GUI by refreshing both admin and user interface and SSH doesn't even start.

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 4.3.6.3
- I have access to my server: *through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: I installed this application
- Using, or trying to install package version/branch: Master and testing
- If upgrading, current package version: *0.175.0~ynh1*

### Steps to reproduce

- Install this app as third party app

### Expected behavior

The app should install without crashing the system

### Logs

https://paste.yunohost.org/raw/igifiyivuy

*If applicable and useful, add screenshots to help explain your problem.*

Some more info: manually rebooting the Raspberry Pi by disconnecting and reconnecting it to the power at least makes Yunohost work again. After that, n8n appears as application, but if you open it, it returns '404 not found, nginx'.

**Comment by Krusty27** [comment]
This is still happening with v0.182.1~ynh1

**Comment by guizmoau** [comment]
Installed v0.182.1~ynh1 on a Raspberry Pi4B 8G today
Yunohost version 11.0.9.7 (stable)

Installation was ok
No particular slow on the system noticed
