### ISSUE TITLE
How can someone help with this project?

### ISSUE THREAD

**Issue by Krusty27** [YunoHost-Apps/n8n_ynh#26]
I see the app development is a bit dead right now, is there something we can do to help?

**Comment by fflorent** [comment]
I thought I could manage with maintaining this project as I used it at some point.

Now, I use [Node-RED](https://github.com/YunoHost-Apps/nodered_ynh) and I am not as involved as I used to be for packaging this app (also I lack a bit of time).

I may have to change the status of the package to **looking for adoption** then.

**Comment by ericgaspar** [comment]
Updating the application seems rather simple -> #27 @Krusty27 If you have time you can push a PR when a new version is available upstream.
