### ISSUE TITLE
SMTP integration

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/n8n_ynh#30]
### Describe the bug

SMTP integration is not active

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- go to `/settings/users`
- in the top right, the following image proves there is no SMTP integration working: ![Screen Shot 2022-08-08 at 12 30 22 PM](https://user-images.githubusercontent.com/42862428/183398580-a791e910-d379-4104-970c-44b5c866640a.jpg)

### Expected behavior

SMTP service should be integrated.

**Comment by ericgaspar** [comment]
Did you try to adapt `.env` file to your SMTP settings?

**Comment by nathanael-h** [comment]
Maybe it is because the variable N8N_SMTP_PASS is empty. 
Is it true that SMTP server when reach locally on port 25 does not need auth? @ericgaspar 
So maybe this PR could help fixing this issue https://github.com/n8n-io/n8n/pull/3742

**Comment by ericgaspar** [comment]
> Is it true that SMTP server when reach locally on port 25 does not need auth? @ericgaspar
As far as I know, yes

**Comment by tituspijean** [comment]
Successfully tested on v1.9.3 with the `Send Email` node set up as in the following screenshot ***and*** "Ignore SSL issues" in the options.

![image](https://github.com/YunoHost-Apps/n8n_ynh/assets/8769166/d69764b8-81ed-4830-ac0c-f11056eda86a)
