### ISSUE TITLE
Allowing app to be public relevant and secure?

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/n8n_ynh#5]
I wonder how secure it is to allow non-registered users to create and execute workflows.

What do you think?

**Comment by ericgaspar** [comment]
I have added the ENV variable `N8N_BASIC_AUTH_ACTIVE=true` in the `.env` file in the testing branch...
https://github.com/YunoHost-Apps/n8n_ynh/blob/f7ca66a78d5d9ddf150e38e46101def8ec5bac62/conf/.env#L14
Fill free to push a PR if you think the `.env` file is missing some important settings.

**Comment by fflorent** [comment]
Ah, right, thank you for the hint and sorry for having bothered you!
