### ISSUE TITLE
Not totally free license

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/n8n_ynh#6]
The license of n8n is **almost** free only. It is under Apache-2 with Commons Clause. See: https://github.com/n8n-io/n8n/blob/master/packages/cli/LICENSE.md (TL;DR: You cannot sell the software, *including without limitation fees for hosting or consulting/ support services related to the Software*)

Note that spdx did not accept the Commons-Clause exception: https://github.com/spdx/license-list-XML/issues/902

**Comment by fflorent** [comment]
Sorry, I lost the main point of my issue xD

I wonder if this license is the good one here:
https://github.com/YunoHost-Apps/n8n_ynh/blob/30cae6f84d9d51481d57c360475d8a040677d95c/manifest.json#L12

Also I don't if that has any impact in the Yunohost app catalog

**Comment by fflorent** [comment]
After discussion, we should rather add this to the manifest:

```json
license: "Apache-2.0 WITH Common-clause"
[...]
{
    "name": "license",
    "type": "alert", # or display_text for 4.2 compatibility
    "style": "danger",
    "ask": { "en": "YOUR TEXT IN MARKDOWN" }
},
```

Compatible only with Yunohost >= 4.3.

**Comment by tituspijean** [comment]
Fixed, we have added an antifeature tag.
